export const STORAGE = {
  USER_TOKEN: "mIZWsYFClS", //al_mahar_user
  SESSION_TIME: "KLlXoZeBxI", //session_time
};

// BBhExzePgp
// eaVOWhFJxa
// VZXMgnfbDW
// zMmOmpYKBr
// ikGEaJGpOq
// skNKHUtBBX
// SQDEZGvQEX
// VTjGXDSmol
// UeNOrTxflY
// wEckwROHJU
// CLhRFEeDLA
// LuHVrZKdoN
// wQQdooVbtX
// RvLKUYhWAe
// ssvAOJjrBe
// NeDXrZghdx
// yHaRBkzptQ
// XqUBIxtdPp
// xAORxUvcXH
// MJZhiBHNQv
// AiRfjBwxgT
// SluqilBSUg
// kiEDtkiTYm
// GfIsPWJwwU
// YQQBlcpKYy
// ruVXPFxxqf
// VEwQDKbkrj
// uknJJAgWbS
// KPIZeNGqDO
// QElbDrSLIC
// cVBiElXtYo
// tJuWyLsMBn
// WlhJtdxfsd
// zfyYuJxMdh
// pzWEaChFZR
// VNrhqlegRj
// ewgnhEqJmi
// XqXVyNrPXd
// HXDPhAPXQc
// poSkJmFELp
// ihhePQbojf
// TPmYpBPOlp
// neGNuzWnhx
// tTBGRRodKw
// bzSYAGWnmW
// HJeUcyuoFP
// nxuYdbqifX
// OBNXozaoNu
// FnOJUjDYXP
// zydAZwkTHM
// TxHVLUnvIB
// CDiAeELNNW
// eMVwybspvL
// GNDoroLYYl
// lYJaXRynzP
// icfCtUdQKM
// tdzpAZOPGC
// TEOhQjaNXT
// LFapmXzuTy
// tRMbmnvFFI
// PDYATRosTE
// SIMtaqVkAN
// IuDkshsXKu
// LJhAwUcGxA
// ShKHBKkmnW
// zPtLegrWsw
// PvAvjfPTnn
// ySFIXfQjau
// UrUtJYaBxb
// EJRUNwbftd
// pLWUYFUMNZ
// BZRoNzSlwD
// VPLlwdDIHG
// pQAxpXldNQ
// RYNXVNLzOn
// zkenDSoigk
// eZanDrhmlW
// fPHqiwRGqy
// dzUIVkHsVu
// hWwWZKenQA
// lOKSbfYArV
// gTbTlgVQIz
// GLciMeNIfc
// HQVBhUSZcS
// KolNljcdfk
// FvDadfPmcE
// yHhDOpQjsx
// xtPSecpmQl
// ypTyoMbhMV
// DOMQnpbmnG
// ADKmXpcFgu
// FSdKPQMcfl
